### ISSUE TITLE
关于 通讯过程中通过在消息头部附加虚拟连接ID来告知网关此消息的去处 的疑惑

### ISSUE THREAD

**Issue by l42111996** [funny/fastway#12]
通讯过程中通过在消息头部附加虚拟连接ID来告知网关此消息的去处
比如做arpg游戏  一张地图在一个进程的一个线程里面   从一个地图切换到另一个地图可能跨线程，这里的一些消息也得发到新的虚拟连接id上去   这样客户端得维护一套消息的去向， 这样感觉客户端在维护服务器的消息路由了，有点别扭，有更好的方案吗？ 达达大神

**Comment by bg5sbk** [comment]
做成配置给到客户端，类似于服务发现机制，客户端跟服务类型耦合，不要跟服务器ID耦合

**Comment by l42111996** [comment]
但是服务器是有状态的 ，如果玩家在一个地图里面这个玩家的移动等消息得发到这个指定的id的服务器。

**Comment by qinlai** [comment]
可以让服务端下发另一个地图的虚拟连接id。我们在做组队系统的时候是这么做的，在玩家换队伍的时候会下发客户端新队伍的虚拟连接id，客户端断开旧的组队虚拟id，连接到新的id。

**Comment by l42111996** [comment]
这样子也可以实现，大部分都是这样做的吗？  我以前是在网关做了个路由   导致网关有很多逻辑  而且有状态。

**Comment by qinlai** [comment]
我们现在项目都是这么做
